FROM python:3.10-alpine
RUN apk add --no-cache bash
RUN apk add gcc musl-dev mariadb-connector-c-dev
WORKDIR /ms_galenos_web_pacientes
COPY ms_galenos_web_pacientes/requirements.txt requirements.txt
RUN pip install -r requirements.txt
EXPOSE 8000
COPY ms_galenos_web_pacientes ms_galenos_web_pacientes
