# Generated by Django 4.2.7 on 2023-12-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api_pacientes", "0002_alter_paciente_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paciente",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
